USE TELEVISIONES

CREATE TABLE INVENTARIOTV(
ID int NOT NULL AUTO_INCREMENT,
ID_SERIE VARCHAR(100),
MARCA VARCHAR(100),
MODELO VARCHAR(100),
TECNOLOGIA VARCHAR(100),
PULGADAS VARCHAR(10),
RESOLUCION VARCHAR(10),
SMART_TV VARCHAR(100),
ROKU VARCHAR(100),
CANTIDAD INT,
PRECIO FLOAT,
PRECIO_DE_VENTA FLOAT,
 PRIMARY KEY (ID)
);
alter table INVENTARIOTV add( VALOR_TOTAL_MERCANCIA float);
alter table INVENTARIOTV add( CATEGORIA VARCHAR(20));
alter table INVENTARIOTV DROP COLUMN CATEGORIA;
SELECT * from  INVENTARIOTV
